<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xipona.Frontend.Redux.TestKit\Xipona.Frontend.Redux.TestKit.csproj" />
    <ProjectReference Include="..\Xipona.Frontend.TestTools\Xipona.Frontend.TestTools.csproj" />
    <ProjectReference Include="..\Xipona.Frontend.WebApp.TestKit\Xipona.Frontend.WebApp.TestKit.csproj" />
    <ProjectReference Include="..\Xipona.Frontend.WebApp\Xipona.Frontend.WebApp.csproj" />
  </ItemGroup>

</Project>
