<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Xipona.Api.Endpoint</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xipona.Api.ApplicationServices\Xipona.Api.ApplicationServices.csproj" />
    <ProjectReference Include="..\Xipona.Api.Contracts\Xipona.Api.Contracts.csproj" />
    <ProjectReference Include="..\Xipona.Api.Domain\Xipona.Api.Domain.csproj" />
    <ProjectReference Include="..\Xipona.Api.Endpoint.Generators\Xipona.Api.Endpoint.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
    <InternalsVisibleTo Include="$(AssemblyName)s.Tests" />
    <InternalsVisibleTo Include="$(AssemblyName).IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

</Project>
