using ProjectHermes.ShoppingList.Frontend.Redux.ItemCategories.States;

namespace ProjectHermes.ShoppingList.Frontend.Redux.ItemCategories.Actions;
public record LoadItemCategoryForEditingFinishedAction(EditedItemCategory ItemCategory);