version: "3.7"

services:
  Database:
    image: postgres:17
    container_name: test-ph-sl-db
    environment:
      POSTGRES_PASSWORD: 123root
      POSTGRES_USER: postgres
    ports:
      - "15906:5432"
    command: -c 'max_connections=400'