using ShoppingList.Frontend.Redux.ShoppingList.States;

namespace ShoppingList.Frontend.Redux.ShoppingList.Actions.TemporaryItemCreator;
public record TemporaryItemSelectedSectionChangedAction(ShoppingListStoreSection Section);