using ShoppingList.Frontend.Redux.ItemCategories.States;

namespace ShoppingList.Frontend.Redux.Items.Actions.Editor.ItemCategorySelectors;
public record LoadInitialItemCategoryFinishedAction(ItemCategorySearchResult ItemCategory);