<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
        <RootNamespace>Xipona.Frontend.WebApp</RootNamespace>
        <Version>0.13.1</Version>
        <PublishTrimmed>false</PublishTrimmed>
        <Nullable>disable</Nullable>
        <UserSecretsId>3fec0ee5-b1d4-47f3-9180-b2d87730c4ec</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AntDesign"/>
        <PackageReference Include="Blazored.LocalStorage"/>
        <PackageReference Include="Fluxor.Blazor.Web"/>
        <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities"/>
        <PackageReference Include="Microsoft.Extensions.Http"/>
        <PackageReference Include="RestEase"/>
        <PackageReference Include="Serilog.Extensions.Logging"/>
        <PackageReference Include="Serilog.Sinks.BrowserHttp"/>
        <PackageReference Include="System.Net.Http"/>
        <PackageReference Include="System.Net.Http.Json"/>
        <PackageReference Include="System.Private.Uri"/>
        <PackageReference Include="System.Text.RegularExpressions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Xipona.Frontend.Infrastructure\Xipona.Frontend.Infrastructure.csproj"/>
        <ProjectReference Include="..\Xipona.Frontend.Redux\Xipona.Frontend.Redux.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\variables.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
