<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Xipona.Api.ArchitectureTests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit.analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xipona.Api.ApplicationServices\Xipona.Api.ApplicationServices.csproj" />
    <ProjectReference Include="..\Xipona.Api.Client\Xipona.Api.Client.csproj" />
    <ProjectReference Include="..\Xipona.Api.Contracts\Xipona.Api.Contracts.csproj" />
    <ProjectReference Include="..\Xipona.Api.Core\Xipona.Api.Core.csproj" />
    <ProjectReference Include="..\Xipona.Api.Domain\Xipona.Api.Domain.csproj" />
    <ProjectReference Include="..\Xipona.Api.Endpoint\Xipona.Api.Endpoint.csproj" />
    <ProjectReference Include="..\Xipona.Api.Repositories\Xipona.Api.Repositories.csproj" />
    <ProjectReference Include="..\Xipona.Api.Secrets\Xipona.Api.Secrets.csproj" />
    <ProjectReference Include="..\Xipona.Api.WebApp\Xipona.Api.WebApp.csproj" />
    <ProjectReference Include="..\Xipona.Api.TestTools\Xipona.Api.TestTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

</Project>
