<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xipona.Frontend.Infrastructure\Xipona.Frontend.Infrastructure.csproj" />
    <ProjectReference Include="..\Xipona.Frontend.TestTools\Xipona.Frontend.TestTools.csproj" />
  </ItemGroup>

</Project>
