<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Xipona.Frontend.Redux.TestKit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xipona.Frontend.Redux\Xipona.Frontend.Redux.csproj" />
    <ProjectReference Include="..\Xipona.Frontend.TestTools\Xipona.Frontend.TestTools.csproj" />
  </ItemGroup>

</Project>
