using Xipona.Frontend.Redux.ItemCategories.States;

namespace Xipona.Frontend.Redux.ItemCategories.Actions;
public record LoadItemCategoryForEditingAction(Guid ItemCategoryId);
public record LoadItemCategoryForEditingStartedAction;
public record LoadItemCategoryForEditingFinishedAction(EditedItemCategory ItemCategory);