namespace Xipona.Frontend.Redux.ShoppingList.Actions.TemporaryItemCreator;
public record SaveTemporaryItemAction;
public record SaveTemporaryItemStartedAction;
public record SaveTemporaryItemFinishedAction;