setx ASPNETCORE_ENVIRONMENT "development"
setx PH_SL_DB_USERNAME_FILE "E:\\dev-ph-shoppinglist-db-username.txt"
setx PH_SL_DB_PASSWORD_FILE "E:\\dev-ph-shoppinglist-db-password.txt"
# setx PH_SL_VAULT_USERNAME_FILE "E:\\dev-ph-shoppinglist-vault-api-username.txt"
# setx PH_SL_VAULT_PASSWORD_FILE "E:\\dev-ph-shoppinglist-vault-api-password.txt"