using ShoppingList.Frontend.Redux.Manufacturers.States;

namespace ShoppingList.Frontend.Redux.Items.Actions.Editor.ManufacturerSelectors;
public record LoadInitialManufacturerFinishedAction(ManufacturerSearchResult Manufacturer);