version: "3.7"

services:
  Database:
    image: postgres:17
    environment:
      POSTGRES_DB: xipona
      POSTGRES_USER_FILE: /run/secrets/xipona-db-username
      POSTGRES_PASSWORD_FILE: /run/secrets/xipona-db-password
    ports:
      - "15909:5432"
    networks: 
      - xipona
    volumes:
      - xipona-database:/var/lib/postgresql/data
    secrets:
      - xipona-db-username
      - xipona-db-password

  Api:
    image: velocir4ptor/xipona-api:0.13.1
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      XIPONA_CORS_ORIGIN__0: 
      XIPONA_DB_USERNAME_FILE: /run/secrets/xipona-db-username
      XIPONA_DB_PASSWORD_FILE: /run/secrets/xipona-db-password
      XIPONA_DB_NAME: xipona
      XIPONA_DB_ADDRESS: Database
      XIPONA_DB_PORT: 5432
      # uncomment this for backend OTEL API key support:
      # XIPONA_OTEL_API_KEY_FILE: /run/secrets/xipona-otel-api-key
      # XIPONA_OTEL_ENDPOINT_LOGS: 
      # XIPONA_OTEL_ENDPOINT_TRACES: 
      # XIPONA_OTEL_API_KEY_HEADER_PREFIX: 
      # uncomment this for vault support
      # XIPONA_VAULT_USERNAME_FILE: /run/secrets/xipona-vault-api-username
      # XIPONA_VAULT_PASSWORD_FILE: /run/secrets/xipona-vault-api-password
      # XIPONA_VAULT_URI: https://myvault.example
      # XIPONA_VAULT_MOUNT_POINT: xipona
      # XIPONA_VAULT_PATHS_DATABASE: database
      # XIPONA_VAULT_PATHS_LOGGING: logging
      # uncomment this for OIDC integration
      # XIPONA_AUTH_ENABLED: "false"
      # XIPONA_AUTH_AUTHORITY: 
      # XIPONA_AUTH_AUDIENCE:
      # XIPONA_AUTH_VALID_TYPES__0: JWT
      # XIPONA_AUTH_CLAIM_NAME: given_name
      # XIPONA_AUTH_CLAIM_ROLE: role
      # XIPONA_AUTH_ROLE_NAME_USER: User
    ports:
      - "12489:80"
    depends_on:
      - Database
    # volumes:
      # - xipona-api-tls:/app/ssl:ro # uncomment this for https support, see readme
    networks:
      - xipona
    secrets:
      - xipona-db-username
      - xipona-db-password
      # - xipona-otel-api-key # uncomment this for backend OTEL API key support
      # - xipona-vault-api-username # uncomment this for vault support
      # - xipona-vault-api-password

  # LogCollector: # uncomment this for frontend log support
  #   image: velocir4ptor/web-assembly-log-collector:1.0.0
  #   ports:
  #     - "13880:80"
  #   volumes:
  #     - xipona-log-collector-config:/app/config:ro
  #     - xipona-log-collector-logs:/app/logs
  #   networks:
  #     - xipona

  Frontend:
    image: velocir4ptor/xipona-frontend:0.13.1
    environment:
      XIPONA_API_URL: http://Api:80/v1
      # uncomment this for log collection
      # XIPONA_LOGS_ENABLED: "false"
      # XIPONA_LOGS_HOST_URL: http://LogCollector:80
      # uncomment this for OIDC integration
      # XIPONA_AUTH_ENABLED: "false"
      # XIPONA_AUTH_AUTHORITY: 
      # XIPONA_AUTH_CLIENT_ID: 
      # XIPONA_AUTH_DEFAULT_SCOPES__0: 
      # XIPONA_AUTH_RESPONSE_TYPE: code
      # XIPONA_AUTH_ROLE_NAME_USER: User
      # XIPONA_AUTH_CLAIM_NAME: given_name
      # XIPONA_AUTH_CLAIM_ROLE: role
      # XIPONA_AUTH_CLAIM_SCOPE: scope
    ports:
      - "14000:80"
    depends_on:
      - Api
    # uncomment this for https support, see readme
    # volumes:
      # - {CONFIG_FOLDER_PATH}/xipona.conf:/etc/nginx/conf.d/xipona.conf:ro
      # - xipona-frontend-tls:/etc/nginx/ssl:ro
    networks:
      - xipona

volumes:
  # xipona-frontend-tls: # uncomment this for https support, see readme
  #   external: true
  # xipona-api-tls:
  #   external: true
  xipona-database:
    external: true
  # xipona-log-collector-config: # uncomment this for frontend log support
  #   external: true
  # xipona-log-collector-logs:
  #   external: true

networks:
  xipona:
    name: xipona

secrets:
  xipona-db-username:
    external: true
  xipona-db-password:
    external: true
  # xipona-otel-api-key: # uncomment this for backend OTEL API key support
  #   external: true