version: "3.7"

services:
  Database:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: change_me
      POSTGRES_USER: xipona
      POSTGRES_DB: xipona
    ports:
      - "15909:3306"
    networks: 
      - xipona
    volumes:
      - xipona-database:/var/lib/postgresql/data

  Api:
    image: velocir4ptor/xipona-api:0.13.1
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      XIPONA_DB_USERNAME: xipona
      XIPONA_DB_PASSWORD: change_me
      # uncomment this for backend OTEL API key support:
      # XIPONA_OTEL_API_KEY: 
      # XIPONA_OTEL_ENDPOINT_LOGS: 
      # XIPONA_OTEL_ENDPOINT_TRACES: 
      # XIPONA_OTEL_API_KEY_HEADER_PREFIX: 
      # uncomment this for vault support:
      # XIPONA_VAULT_USERNAME: /run/secrets/xipona-vault-api-username
      # XIPONA_VAULT_PASSWORD: /run/secrets/xipona-vault-api-password
      # XIPONA_VAULT_URI: https://myvault.example
      # XIPONA_VAULT_MOUNT_POINT: xipona
      # XIPONA_VAULT_PATHS_DATABASE: database
      # XIPONA_VAULT_PATHS_LOGGING: logging
    ports:
      - "12489:80"
    depends_on:
      - Database
    volumes:
      # - xipona-api-tls:/app/ssl:ro # uncomment this for https support, see readme
      - xipona-api-config:/app/config:ro
    networks:
      - xipona

  # LogCollector: # uncomment this for frontend log support
  #   image: velocir4ptor/web-assembly-log-collector:1.0.0
  #   ports:
  #     - "13880:80"
  #   volumes:
  #     - xipona-log-collector-config:/app/config:ro
  #     - xipona-log-collector-logs:/app/logs
  #   networks:
  #     - xipona

  Frontend:
    image: velocir4ptor/xipona-frontend:0.13.1
    ports:
      - "14000:80"
    depends_on:
      - Api
    volumes:
      - xipona-frontend-config:/etc/nginx/conf.d:ro
      - {CONFIG_FOLDER_PATH}/appsettings.Production.json:/usr/share/nginx/html/wwwroot/appsettings.Production.json:ro
      # - xipona-frontend-tls:/etc/nginx/ssl:ro # uncomment this for https support, see readme
    networks:
      - xipona

volumes:
  # xipona-frontend-tls: # uncomment this for https support, see readme
  #   external: true
  # xipona-api-tls:
  #   external: true
  xipona-frontend-config:
    external: true
  xipona-api-logs:
    external: true
  xipona-api-config:
    external: true
  xipona-database:
    external: true
  # xipona-log-collector-config: # uncomment this for frontend log support
  #   external: true
  # xipona-log-collector-logs:
  #   external: true

networks:
  xipona:
    name: xipona