<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Xipona.Frontend.Redux</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="Fluxor.Blazor.Web" />
    <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="RestEase" />
    <PackageReference Include="Xipona.Api.Contracts" />
  </ItemGroup>

</Project>
