<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Xipona.Frontend.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="RestEase" />
    <PackageReference Include="WebAssembly.Bindings" />
    <PackageReference Include="Xipona.Api.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xipona.Frontend.Redux\Xipona.Frontend.Redux.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Xipona.Api.Client">
      <HintPath>..\Xipona.Frontend.WebApp\Xipona.Api.Client.dll</HintPath>
    </Reference>
    <Reference Include="Xipona.Api.Contracts">
      <HintPath>..\Xipona.Frontend.WebApp\Xipona.Api.Contracts.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
  </ItemGroup>

</Project>
