namespace Xipona.Frontend.Redux.Items.Actions.Search;
public record RetrieveSearchResultCountAction;
public record RetrieveSearchResultCountStartedAction;
public record RetrieveSearchResultCountFinishedAction(int Count);