name: Test-Build
on:
  push:
    branches: [ "features/#512" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  docker-image-api:
    name: Docker Image Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: ./Api
          file: ./Api/Dockerfile
          push: false
          tags: velocir4ptor/ph-xipona-api:0.13.0-alpha.1
