<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Xipona.Api.TestTools</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="AutoFixture.AutoMoq" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="DeepCloner" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Neovolve.Logging.Xunit.v3" />
    <PackageReference Include="ObjectsComparer" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
      <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

</Project>
